"""Golden-output tests for the estampo.toml adapter."""

from __future__ import annotations

from augura.estampo import to_estampo_toml
from augura.report import Finding, Report, Severity


def _overhang() -> Finding:
    return Finding(kind="overhang", severity=Severity.WARNING, message="needs support", area=100.0)


def _brim() -> Finding:
    return Finding(kind="brim", severity=Severity.WARNING, message="recommend a brim")


def _min_feature() -> Finding:
    return Finding(
        kind="min_feature", severity=Severity.WARNING, message="0.2 mm caps layer height"
    )


def _not_manifold() -> Finding:
    return Finding(kind="not_manifold", severity=Severity.ERROR, message="not watertight")


def _bed_fit() -> Finding:
    return Finding(kind="bed_fit", severity=Severity.ERROR, message="exceeds build volume")


def _tip_over() -> Finding:
    return Finding(kind="tip_over", severity=Severity.ERROR, message="will topple")


# --- clean report ---


def test_clean_report() -> None:
    result = to_estampo_toml(Report())
    assert result == (
        "# Generated by augura — printability analysis\n"
        "# Adjust values before using with estampo.\n"
        "\n"
        "enable_support = false\n"
        'brim_type = "no_brim"\n'
    )


# --- individual findings ---


def test_enable_support_true_when_overhang() -> None:
    result = to_estampo_toml(Report(findings=(_overhang(),)))
    assert "enable_support = true" in result


def test_enable_support_false_when_no_overhang() -> None:
    result = to_estampo_toml(Report())
    assert "enable_support = false" in result


def test_brim_type_brim_when_brim_finding() -> None:
    result = to_estampo_toml(Report(findings=(_brim(),)))
    assert 'brim_type = "brim"' in result


def test_brim_type_no_brim_when_no_brim_finding() -> None:
    result = to_estampo_toml(Report())
    assert 'brim_type = "no_brim"' in result


# --- slicer.overrides section ---


def test_no_overrides_section_when_clean() -> None:
    result = to_estampo_toml(Report())
    assert "[slicer.overrides]" not in result


def test_overrides_section_for_min_feature() -> None:
    result = to_estampo_toml(Report(findings=(_min_feature(),)))
    assert "[slicer.overrides]" in result
    assert "layer height" in result


def test_overrides_section_for_not_manifold() -> None:
    result = to_estampo_toml(Report(findings=(_not_manifold(),)))
    assert "[slicer.overrides]" in result
    assert "Non-manifold" in result


def test_overrides_section_for_bed_fit() -> None:
    result = to_estampo_toml(Report(findings=(_bed_fit(),)))
    assert "[slicer.overrides]" in result
    assert "build volume" in result


def test_overrides_section_for_tip_over() -> None:
    result = to_estampo_toml(Report(findings=(_tip_over(),)))
    assert "[slicer.overrides]" in result
    assert "stability" in result


# --- orient parameter ---


def test_orient_omitted_when_none() -> None:
    result = to_estampo_toml(Report())
    assert "orient" not in result


def test_orient_emitted_when_supplied() -> None:
    result = to_estampo_toml(Report(), orient=(0.0, 90.0, 0.0))
    assert "orient = [0, 90, 0]" in result


def test_orient_appears_before_enable_support() -> None:
    result = to_estampo_toml(Report(), orient=(0.0, 0.0, 0.0))
    assert result.index("orient") < result.index("enable_support")


# --- golden full output ---


def test_golden_full_report() -> None:
    report = Report(findings=(_overhang(), _brim(), _min_feature()))
    result = to_estampo_toml(report, orient=(0.0, 90.0, 0.0))
    assert result == (
        "# Generated by augura — printability analysis\n"
        "# Adjust values before using with estampo.\n"
        "\n"
        "orient = [0, 90, 0]\n"
        "enable_support = true\n"
        'brim_type = "brim"\n'
        "\n"
        "[slicer.overrides]\n"
        "# Thin vertical features detected — consider reducing layer height\n"
    )


# --- no estampo import ---


def test_no_estampo_runtime_import() -> None:
    import sys

    assert not any(mod.startswith("estampo") for mod in sys.modules), (
        "augura.estampo must not import estampo at runtime"
    )
