"""estampo.toml output adapter.

Turns an augura :class:`~augura.report.Report` into an ``estampo.toml`` fragment
so augura's findings can optionally configure an estampo slice. This is a
**pure, one-way data transform** — augura never imports or calls estampo at
runtime; it only emits text.

The exact estampo key names and value enums should be verified against the
current estampo schema; this emits a best-effort fragment. ``orient`` is not set
here because it comes from orientation search (a multi-pose result), not a
single-pose report.
"""

from __future__ import annotations

from augura.report import Report


def to_estampo_toml(report: Report) -> str:
    """Emit an estampo.toml fragment derived from a printability report."""
    lines = [
        "# Generated by augura - verify keys/values against your estampo schema.",
        f"enable_support = {'true' if report.overhangs else 'false'}",
    ]
    if report.brim:
        lines.append('brim_type = "brim"')
    return "\n".join(lines) + "\n"
