"""estampo.toml output adapter.

Pure data transform: turns an augura ``Report`` into an estampo.toml fragment.
No estampo import — augura stays independently installable.
"""

from __future__ import annotations

from augura.report import Report


def to_estampo_toml(
    report: Report,
    *,
    orient: tuple[float, float, float] | None = None,
    source: str | None = None,
) -> str:
    """Return an estampo.toml fragment derived from *report*.

    Args:
        report: The printability report produced by :func:`augura.analyze`.
        orient: Optional ``(X, Y, Z)`` Euler rotation in degrees for the chosen
            print orientation, e.g. from :func:`augura.orientation_scores`.
            Applied as build123d's ``Rotation`` does: intrinsic rotations about
            X, then Y, then Z. Omitted from the output when *None*.
        source: Optional name of the analysed input file, recorded in the
            fragment's header comment.

    The fragment contains:

    * ``orient`` — the chosen rotation, if supplied.
    * ``enable_support`` — ``true`` when overhangs were detected.
    * ``brim_type`` — ``"brim"`` when lift/peel risk was detected, else
      ``"no_brim"``.
    * ``[slicer.overrides]`` — a section with advisory comments when thin
      features, manifold issues, or bed-fit problems are present; omitted when
      the report is clean.
    """
    # Collapse whitespace (a newline would break out of the TOML comment).
    provenance = f" from {' '.join(source.split())}" if source else ""
    lines: list[str] = [
        f"# Generated by augura{provenance} — printability analysis",
        "# Adjust values before using with estampo.",
        "",
    ]

    if orient is not None:
        x, y, z = orient
        # .10g keeps axis angles clean ("180", not "180.0") without rounding
        # away the precision the part was actually analysed at.
        lines.append(f"orient = [{x:.10g}, {y:.10g}, {z:.10g}]")

    lines.append(f"enable_support = {str(bool(report.overhangs)).lower()}")
    brim_type = "brim" if report.brim else "no_brim"
    lines.append(f'brim_type = "{brim_type}"')

    # Advisory [slicer.overrides] section — only emit when there is something
    # to say so that a clean report produces a minimal fragment.
    advisories: list[str] = []
    if report.min_feature:
        advisories.append("# Thin vertical features detected — consider reducing layer height")
    if report.manifold_issues:
        advisories.append("# Non-manifold geometry detected — repair before slicing")
    if report.bed_fit:
        advisories.append("# Part exceeds build volume — rescale or split before slicing")
    if report.tip_over:
        advisories.append("# Tip-over risk — add a brim or raft for stability")

    if advisories:
        lines.append("")
        lines.append("[slicer.overrides]")
        lines.extend(advisories)

    return "\n".join(lines) + "\n"
